services:
  postgres:
    image: postgres:latest
    container_name: nest_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      retries: 5

  nestjs-app:
    build:
      context: ../crud-task 
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: tasks_db
    volumes:
      - ../crud-task:/app
      - /app/node_modules
    command: ["npm", "run", "start"]

volumes:
  postgres_data:
