version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nest_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: nest_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5

  nestjs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: tasks_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - nestjs_data:/app
    command: [ "sh", "-c", "cd /app && npm run start" ]

volumes:
  postgres_data:
  redis_data:
  nestjs_data:
